spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/libraryx
    username: postgres
    password: Rx199630
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # PostgreSQL için ek yapılandırmalar
  sql:
    init:
      mode: always
server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true